"""Stitch the tutorial-09 elongation into a VMD movie + draw the analytic tunnel.

Like ``cosmo-elongate-movie`` (it reuses that tool's stitcher for the growing
chain), but the generated ``movie.tcl`` **also draws the analytic exit tunnel as
designed** -- the cylindrical bore, the closed PTC end, and the infinite exit-face
wall (a flat annulus whose hole is the bore). The tunnel geometry is read from the
**same** ``elongate.ini`` used for the run, so the drawn tunnel always matches the
forces the chain actually felt (PLAN.md §2-§4).

There are no ribosome beads in cylinder mode, so the tunnel is pure VMD
``graphics`` (drawn once, on its own static molecule) rather than loaded scenery.

Usage (run from this folder, after the elongation finishes)::

    python make_movie_cylinder.py -o synth_out -f elongate.ini
    vmd -e synth_out/movie.tcl
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Optional, Tuple

# Reuse the shipped, unchanged stitcher for the growing-chain DCD/PSF; we only
# replace the generated .tcl with a tunnel-aware one.
from cosmo.translation.make_movie import stitch_movie

# The tutorial's own config reader (tunnel geometry lives in elongate.ini).
from cylinder import read_elongate_config

# nm (the run / params) -> angstrom (VMD and the stitched DCD/PSF).
NM_TO_A = 10.0


def make_cylinder_movie(out_root: str, ini: str, out_prefix: str = "movie",
                        park: str = "sentinel", outname: str = "traj",
                        wall_outer_nm: Optional[float] = None,
                        verbose: bool = True) -> Tuple[str, str, str]:
    """Stitch the movie and write a tunnel-aware ``movie.tcl``.

    Parameters
    ----------
    out_root : str
        Elongation run output root (contains the ``L_<L>/`` folders).
    ini : str
        The ``elongate.ini`` used for the run (source of the tunnel geometry).
    out_prefix, park, outname
        Passed straight through to
        :func:`cosmo.translation.make_movie.stitch_movie`.
    wall_outer_nm : float, optional
        Outer radius (nm) of the drawn exit-face annulus. None -> ``r + 3 nm``.

    Returns
    -------
    (psf_path, dcd_path, tcl_path)
    """
    # 1. Stitch the per-length DCDs exactly like cosmo-elongate-movie (no ribosome
    #    beads in cylinder mode). This writes movie.{psf,dcd} and a default .tcl.
    psf, dcd, tcl = stitch_movie(out_root, out_prefix=out_prefix, park=park,
                                 outname=outname, ribosome_pdb=None,
                                 verbose=verbose)

    # 2. Read the tunnel geometry from the same INI that drove the run.
    p = read_elongate_config(ini, verbose=False).params
    x_lo = p.tunnel_x_lo_nm
    x_exit = x_lo + p.tunnel_length_nm
    r = p.tunnel_radius_nm
    y0, z0 = p.tunnel_center_nm
    rho = p.tunnel_mouth_round_nm
    wall_outer = (r + 3.0) if wall_outer_nm is None else wall_outer_nm

    # 3. Overwrite the default .tcl with a tunnel-aware version.
    _write_tcl_cylinder(tcl, os.path.basename(psf), os.path.basename(dcd),
                        park=park, x_lo_nm=x_lo, x_exit_nm=x_exit, r_nm=r,
                        y0_nm=y0, z0_nm=z0, rho_nm=rho, wall_outer_nm=wall_outer)
    if verbose:
        print(f"Tunnel-aware VMD script: {tcl}")
        print(f"  bore r={r} nm, x in [{x_lo}, {x_exit}] nm, axis (y,z)=({y0},{z0}) nm")
        print("")
        print(f"View it with:  vmd -e {tcl}")
    return psf, dcd, tcl


def _write_tcl_cylinder(path: str, psf_name: str, dcd_name: str, park: str,
                        x_lo_nm: float, x_exit_nm: float, r_nm: float,
                        y0_nm: float, z0_nm: float, rho_nm: float,
                        wall_outer_nm: float) -> None:
    """Write a VMD script: growing chain (as make_movie) + the analytic tunnel."""
    # Chain reps mirror cosmo.translation.make_movie's sentinel/cterm scheme.
    if park == "sentinel":
        sel = "not (x > 9000)"
        hide_note = ("# Not-yet-synthesized beads are parked far away and hidden "
                     "each frame.")
    else:
        sel = "all"
        hide_note = "# 'cterm' parking: future beads stacked on the C-terminus."

    # nm -> angstrom (the stitched DCD/PSF are in angstrom).
    xlo = x_lo_nm * NM_TO_A
    xexit = x_exit_nm * NM_TO_A
    r = r_nm * NM_TO_A
    y0 = y0_nm * NM_TO_A
    z0 = z0_nm * NM_TO_A
    rho = rho_nm * NM_TO_A
    rout = wall_outer_nm * NM_TO_A
    cap_thick = max(0.3 * r, 1.0)   # thin filled disk for the closed PTC end

    tcl = f"""# VMD visualization of the tutorial-09 elongation + the analytic exit tunnel.
# Generated by make_movie_cylinder.py.
#   vmd -e {os.path.basename(path)}      (run from this folder)
#
# Two molecules: (0) the growing nascent chain (the stitched movie), and
# (1) the analytic tunnel drawn as static graphics -- the cylindrical bore, the
# closed PTC end cap, and the infinite exit-face wall (a flat annulus whose hole
# is the bore). Geometry is read from elongate.ini, in nm, drawn here in angstrom.

# ------------------------------------------------------------------ chain
mol new {psf_name} type psf waitfor all
mol addfile {dcd_name} type dcd waitfor all
mol rename top "nascent_chain"
mol delrep 0 top

{hide_note}
# Beads (VDW), colored by ResID so the growing chain reads as an N->C gradient.
mol representation VDW 1.5 16.0
mol color ResID
mol selection {{{sel}}}
mol material Opaque
mol addrep top
mol selupdate 0 top on

# Backbone trace.
mol representation Licorice 0.4 16.0
mol color ResID
mol selection {{{sel}}}
mol addrep top
mol selupdate 1 top on

set chainmol [molinfo top]

# ------------------------------------------------------------------ tunnel
# A flat annulus (filled ring) in the y-z plane at x = xpos: inner radius rin
# (the bore mouth), outer radius rout (the "infinite" wall). The hole IS the bore.
proc draw_annulus {{mol xpos cy cz rin rout n}} {{
    set pi 3.141592653589793
    set da [expr {{2.0 * $pi / $n}}]
    for {{set i 0}} {{$i < $n}} {{incr i}} {{
        set a0 [expr {{$i * $da}}]
        set a1 [expr {{($i + 1) * $da}}]
        set yi0 [expr {{$cy + $rin  * cos($a0)}}]; set zi0 [expr {{$cz + $rin  * sin($a0)}}]
        set yi1 [expr {{$cy + $rin  * cos($a1)}}]; set zi1 [expr {{$cz + $rin  * sin($a1)}}]
        set yo0 [expr {{$cy + $rout * cos($a0)}}]; set zo0 [expr {{$cz + $rout * sin($a0)}}]
        set yo1 [expr {{$cy + $rout * cos($a1)}}]; set zo1 [expr {{$cz + $rout * sin($a1)}}]
        graphics $mol triangle "$xpos $yi0 $zi0" "$xpos $yo0 $zo0" "$xpos $yo1 $zo1"
        graphics $mol triangle "$xpos $yi0 $zi0" "$xpos $yo1 $zo1" "$xpos $yi1 $zi1"
    }}
}}

set tun [mol new]
mol rename $tun "tunnel"

# Bore wall: a hollow tube (no end caps) from the PTC to the exit, axis along +x.
graphics $tun material Transparent
graphics $tun color blue
graphics $tun cylinder "{xlo:.3f} {y0:.3f} {z0:.3f}" "{xexit:.3f} {y0:.3f} {z0:.3f}" \\
    radius {r:.3f} resolution 60 filled no

# Closed PTC end: a thin filled disk capping the bore at x_lo.
graphics $tun color red
graphics $tun cylinder "{xlo - cap_thick:.3f} {y0:.3f} {z0:.3f}" "{xlo:.3f} {y0:.3f} {z0:.3f}" \\
    radius {r:.3f} resolution 60 filled yes

# Infinite exit-face wall at x_exit: a flat annulus (inner = bore radius, so a
# cytosol bead can re-enter only through the hole).
graphics $tun material Glass3
graphics $tun color gray
draw_annulus $tun {xexit:.3f} {y0:.3f} {z0:.3f} {r:.3f} {rout:.3f} 96

# (mouth fillet radius rho = {rho:.2f} A -- the rounded inner corner is a
#  sub-angstrom detail of the force, not drawn.)

# ------------------------------------------------------------------ view
mol top $chainmol
set nf [molinfo $chainmol get numframes]
if {{$nf > 0}} {{
    animate goto [expr {{$nf - 1}}]
    display resetview
    animate goto 0
}}

axes location off
display projection Orthographic
color Display Background white
animate speed 0.85

puts "Loaded $nf frames + the analytic tunnel (bore r={r:.1f} A, x in \\[{xlo:.1f}, {xexit:.1f}\\] A)."
puts "Press Play to watch the chain thread the bore and emerge past the exit wall."
"""
    with open(path, "w") as fh:
        fh.write(tcl)


def main(argv: Optional[list] = None) -> None:
    """CLI: ``python make_movie_cylinder.py -o synth_out -f elongate.ini``."""
    ap = argparse.ArgumentParser(
        prog="make_movie_cylinder.py",
        description="Stitch the tutorial-09 per-length elongation trajectories into "
                    "one VMD movie (like cosmo-elongate-movie) AND draw the analytic "
                    "exit tunnel (bore + PTC cap + exit-face wall) read from "
                    "elongate.ini, so the chain is seen threading the tunnel.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("-o", "--out-root", required=True,
                    help="elongation run output root (contains the L_<L>/ folders).")
    ap.add_argument("-f", "--ini", default="elongate.ini",
                    help="the elongate.ini used for the run (tunnel geometry source).")
    ap.add_argument("--prefix", default="movie",
                    help="basename for the stitched movie files.")
    ap.add_argument("--park", default="sentinel", choices=["sentinel", "cterm"],
                    help="where to put not-yet-synthesized beads each frame.")
    ap.add_argument("--outname", default="traj",
                    help="per-length output basename used by the runner.")
    ap.add_argument("--wall-outer", type=float, default=None,
                    help="outer radius of the drawn exit-face wall (nm; default r+3).")
    if argv is None and len(sys.argv) == 1:
        ap.print_help()
        sys.exit(0)
    args = ap.parse_args(argv)
    make_cylinder_movie(args.out_root, args.ini, out_prefix=args.prefix,
                        park=args.park, outname=args.outname,
                        wall_outer_nm=args.wall_outer)


if __name__ == "__main__":
    main()
