"""
Generate multiple chains of protein for LLPS simulation.
This script requires BioPython, PeptideBuilder and MDAnalysis.

The parameters user can modify is defined in USER_DEFINE section.
"""
import Bio.PDB
import MDAnalysis as mda
import PeptideBuilder
import numpy as np
from PeptideBuilder import Geometry
from mdtraj.utils.rotation import rotation_matrix_from_quaternion


def tile_universe(universe, n_x, n_y):
    """
    tile universe: load universe of single chain and then make n_x*n_y copy.

    Parameters
    ----------
    universe: Original universe which contains single chain
    n_x: copy as x dimension
    n_y: copy as y dimension

    Returns
    -------
    new_universe: universe contains n_x*n_y chains of original chain.

    """
    chain_list = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
                  'U', 'V', 'W', 'X', 'Y', 'Z']

    n_atoms = len(list(universe.atoms))
    print(f"number of atoms in model: {n_atoms}")
    copied = []
    for x in range(n_x):
        for y in range(n_y):
            u_ = universe.copy()
            # distance in (x,y) coordinates are 10 angstrom apart between each chain.
            move_by = np.array([10, 10, 10]) * (x, y, 0)
            # print(move_by)
            u_.atoms.translate(move_by)
            u_.add_TopologyAttr('chainID', n_atoms * [chain_list[(x * n_x + y) % len(chain_list)]])
            u_.add_TopologyAttr('segid', [chain_list[(x * n_x + y) % len(chain_list)]])
            copied.append(u_.atoms)

    new_universe = mda.Merge(*copied)
    new_box = np.max(new_universe.atoms.positions, axis=0) - np.min(new_universe.atoms.positions, axis=0)
    new_universe.dimensions = list(new_box) + [90] * 3
    return new_universe


def buildTemplateSingleChain(fasta):
    geo = Geometry.geometry(fasta[0])
    geo.phi = -120
    geo.psi_im1 = 150

    structure = PeptideBuilder.initialize_res(geo)
    for residue in fasta[1:]:
        structure = PeptideBuilder.add_residue(structure, residue, geo.phi, geo.psi_im1)

    out = Bio.PDB.PDBIO()
    out.set_structure(structure)
    ca_coords = []
    for residue in out.structure.get_residues():
        atoms = residue.get_atoms()
        for atom in atoms:
            if atom.name == 'CA':
                ca_coords.append([atom.coord[0], atom.coord[1], atom.coord[2]])

    ca_coords = np.array(ca_coords)

    # collect coordinate of all atoms generated by PeptideBuilder
    xyz = []
    for atom in out.structure.get_atoms():
        xyz.append([atom.coord[0], atom.coord[1], atom.coord[2]])
    xyz = np.array(xyz)
    # get the vector made by CA atoms of the first and last residues, then translate the molecule to parallel to Z-axis
    v = ca_coords[-1] - ca_coords[0]
    u = np.array([0, 0, 1])
    a = np.cross(v, u)
    a = a / np.linalg.norm(a, keepdims=True)
    b = np.arccos(np.dot(v, u) / np.linalg.norm(v))
    quaternion = np.insert(np.sin(-b / 2).reshape(-1, 1) * a, 0, np.cos(-b / 2), axis=1)
    translated_coord = xyz - np.mean(xyz, axis=0)
    translated_coord = np.matmul(translated_coord, rotation_matrix_from_quaternion(quaternion))
    xyz = np.array(translated_coord[0])

    # translate molecule to the origin
    xyz -= np.min(xyz, axis=0)

    # replace coordinate generated by PeptideBuilder by new coordinate
    for i, atom in enumerate(structure.get_atoms()):
        atom.coord = xyz[i]

    out.set_structure(structure)
    out.save("model_1chain.pdb")


# Main program
"""
USER_DEFINE
User can change following parameters:
"""
seq = 'MASNDYTQQATQSYGAYPTQPGQGYSQQSSQPYGQQSYSGYSQSTDTSGYGQSSYSSYGQSQNTGYGTQSTPQGYGSTGGYGSSQSSQSSYGQQSSYPGYGQQPAPSSTSGSYGSSSQSSSYGQPQSGSYSQQPSYGGQQQSYGQQQSYNPPQGYGQQNQYNS'
protein_name = "FUS"
# number of chains = nx*ny
nx = 20
ny = 5

# build model structure
print("\n")
print("Building model structure of 1 chain from fasta sequence")
buildTemplateSingleChain(seq)
print("Done")
print("===========================")

print(f"Making {nx * ny} copies from model structure ...")
protein = mda.Universe('model_1chain.pdb')

tiled = tile_universe(protein, nx, ny)
all_atoms = tiled.select_atoms('all')
all_atoms.write(f'{protein_name}_{nx * ny}chains.pdb')
print("Done")
print("===========================")
