# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# Make the `cosmo` package importable for autodoc (repo root is the parent dir).
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = u'COSMO'
copyright = u'2022, Quyen Vu'
author = u'Quyen Vu'

# Release version — CalVer YEAR.N (see scripts/next_version.sh). Auto-derived, never
# hand-edited per release: on a CI tag build use the pushed tag; otherwise the newest
# YEAR.N tag in git; else a YEAR.dev marker.
import datetime


def _release_version():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # Read the version straight from git via setuptools-scm (the release source of
    # truth). On the exact tag commit this is the clean CalVer (e.g. "2026.1");
    # between tags it is a derived dev version. Needs the repo's tags in the
    # checkout (the docs CI fetches full history + tags).
    try:
        from setuptools_scm import get_version
        return get_version(root=root, local_scheme='no-local-version')
    except Exception:
        pass
    # Fallback: the installed package's recorded version.
    try:
        from importlib.metadata import version as _dist_version
        return _dist_version('cosmo')
    except Exception:
        pass
    return datetime.datetime.utcnow().strftime('%Y') + '.dev'


version = release = _release_version()


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# See: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
autodoc_default_options = {
    # 'members': True,
    #'undoc-members': True,
    'private-members': True,
    #'special-members': True,
    #'inherited-members': True,
    #'show-inheritance': True
}

autosummary_generate = True

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
#    'numpydoc', # automatically includes `sphinx.ext.autosummary`
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
    'myst_parser',  # Markdown support + the {include} directive used by the tutorials
]

# The tutorial index ``{include}``s the repo's GitHub-facing tutorial READMEs, whose
# links are **repo-relative** (e.g. ``./07_csp_cylinder/`` and ``../README.md``) so they
# work when browsing the tutorials on GitHub. MyST cannot resolve those as in-doc
# cross-references, and the same READMEs jump heading levels (H1 -> H3). Neither is a
# real docs defect, so silence just those two MyST warning categories to keep the build
# clean; every autodoc/docstring/reference warning is still reported.
suppress_warnings = ['myst.xref_missing', 'myst.header']


#mathjax_config = {
#    'extensions': ['tex2jax.js'],
#    'jax': ['input/TeX', 'output/HTML-CSS'],
#}

# Sidebars: let the Furo theme supply its own (brand, search, scroll, toc).


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

# Furo theme options. Full-width layout is achieved by overriding Furo's
# --content-width CSS variable (see _static/custom.css for the rest). The source
# links replace the old RTD "Edit on GitHub" / version machinery.
html_theme_options = {
    'light_css_variables': {
        # Let the article column use the full available width. Furo prepends ``--`` to
        # each key, so the key here must NOT include it (``content-width`` ->
        # ``--content-width``); writing ``--content-width`` yields an invalid
        # ``----content-width`` that is silently ignored.
        'content-width': '100%',
    },
    'dark_css_variables': {
        'content-width': '100%',
    },
    'navigation_with_keys': True,
    'source_repository': 'https://github.com/vuqv/cosmo/',
    'source_branch': 'main',
    'source_directory': 'docs/',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom.css']
html_logo = "_static/logo.svg"        # the bead-chain mark; Furo shows it above the title
html_favicon = "_static/favicon.svg"  # same mark, for the browser tab
# No html_title override -> Furo uses the default "COSMO <release> documentation",
# so the CalVer release version (e.g. 2026.1) shows in the title.
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'cosmodoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'cosmo.tex', 'COSMO Documentation',
     'COSMO', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'cosmo', 'COSMO Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'cosmo', 'COSMO Documentation',
     author, 'cosmo', 'Coarse-grained simulation package for intrinsically disordered proteins.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------
# The previous RTD "lower-left" multi-version/language switcher (GitPython +
# _templates/versions.html) was specific to sphinx_rtd_theme and is not used by
# Furo. Source/"Edit" links are configured via html_theme_options
# (source_repository / source_branch / source_directory) above.
today_fmt = "%B %d, %Y"
